title: Tyler Alexander # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MD-PhD candidate | neuroscience, biophysics, neurosurgery
  <br><br>
  I'm Tyler Alexander. Ever since I was young, I wanted to enter the field of medicine; to me, there is nothing more powerful than the ability to make a positive impact in someone's life – while working with a team of folks oriented around the same goal. I believe in the power of working across disciplines, to facilitate change and foster innovation. I am inspired by "how" and "why" things work; I believe it is essential to understand fundamental workings of processes, if we are to drive progress and create life-altering inventions.
  <br><br>
  <a href="https://twitter.com/Ty_Alexand">View My Twitter Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
